### ISSUE TITLE
ssh kernel not working with ipython 9.0

### ISSUE THREAD

**Issue by bcornec** [Workshops-on-Demand/wod-backend#96]
https://ipython.readthedocs.io/en/stable/ shows that  new release occured the 28th of februaray, which is breaking the installation of the ssh kernel :-(

```
fatal: [wod-backend11.hpedev-floss-wod.lab]: FAILED! => {"changed": true, "cmd": ". '/opt/jupyterhub/bin/activate' && python3 -m sshkernel install --sys-prefix", "delta": "0:00:01.103558", "end": "2025-03-02 16:42:05.947620", "msg": "non-zero return code", "rc": 1, "start": "2025-03-02 16:42:04.844062", "stderr": "Traceback (most recent call last):\n  File \"/opt/jupyterhub/lib/python3.12/site-packages/metakernel/_metakernel.py\", line 36, in <module>\n    from IPython.utils.PyColorize import NeutralColors\nImportError: cannot import name 'NeutralColors' from 'IPython.utils.PyColorize' (/opt/jupyterhub/lib/python3.12/site-packages/IPython/utils/PyColorize.py)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 189, in _run_module_as_main\n  File \"<frozen runpy>\", line 148, in _get_module_details\n  File \"<frozen runpy>\", line 112, in _get_module_details\n  File \"/opt/jupyterhub/lib/python3.12/site-packages/sshkernel/__init__.py\", line 3, in <module>\n    from .kernel import ExceptionWrapper\n  File \"/opt/jupyterhub/lib/python3.12/site-packages/sshkernel/kernel.py\", line 7, in <module>\n    from metakernel import ExceptionWrapper\n  File \"/opt/jupyterhub/lib/python3.12/site-packages/metakernel/__init__.py\", line 2, in <module>\n    from ._metakernel import (\n  File \"/opt/jupyterhub/lib/python3.12/site-packages/metakernel/_metakernel.py\", line 40, in <module>\n    from IPython.core.excolors import TermColors\nModuleNotFoundError: No module named 'IPython.core.excolors'", "stderr_lines": ["Traceback (most recent call last):", "  File \"/opt/jupyterhub/lib/python3.12/site-packages/metakernel/_metakernel.py\", line 36, in <module>", "    from IPython.utils.PyColorize import NeutralColors", "ImportError: cannot import name 'NeutralColors' from 'IPython.utils.PyColorize' (/opt/jupyterhub/lib/python3.12/site-packages/IPython/utils/PyColorize.py)", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"<frozen runpy>\", line 189, in _run_module_as_main", "  File \"<frozen runpy>\", line 148, in _get_module_details", "  File \"<frozen runpy>\", line 112, in _get_module_details", "  File \"/opt/jupyterhub/lib/python3.12/site-packages/sshkernel/__init__.py\", line 3, in <module>", "    from .kernel import ExceptionWrapper", "  File \"/opt/jupyterhub/lib/python3.12/site-packages/sshkernel/kernel.py\", line 7, in <module>", "    from metakernel import ExceptionWrapper", "  File \"/opt/jupyterhub/lib/python3.12/site-packages/metakernel/__init__.py\", line 2, in <module>", "    from ._metakernel import (", "  File \"/opt/jupyterhub/lib/python3.12/site-packages/metakernel/_metakernel.py\", line 40, in <module>", "    from IPython.core.excolors import TermColors", "ModuleNotFoundError: No module named 'IPython.core.excolors'"], "stdout": "", "stdout_lines": []}
```

**Comment by bcornec** [comment]
Hummm, however, my test is on a machine where ipython is older:
`pip3 list | grep python
[...]
ipython                     8.20.0
[...]`

So maybe something else :-(
It's on  a lab machine installed during AlpOSS, so modules have not changed since and it was working there. So maybe another of my very recent modifications.

**Comment by bcornec** [comment]
`wodadmin@wod-backend11:~$ . /opt/jupyterhub/bin/activate 
(jupyterhub) wodadmin@wod-backend11:~$ python3 -m sshkernel install --sys-prefix
Traceback (most recent call last):
  File "/opt/jupyterhub/lib/python3.12/site-packages/metakernel/_metakernel.py", line 36, in <module>
    from IPython.utils.PyColorize import NeutralColors
ImportError: cannot import name 'NeutralColors' from 'IPython.utils.PyColorize' (/opt/jupyterhub/lib/python3.12/site-packages/IPython/utils/PyColorize.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/opt/jupyterhub/lib/python3.12/site-packages/sshkernel/__init__.py", line 3, in <module>
    from .kernel import ExceptionWrapper
  File "/opt/jupyterhub/lib/python3.12/site-packages/sshkernel/kernel.py", line 7, in <module>
    from metakernel import ExceptionWrapper
  File "/opt/jupyterhub/lib/python3.12/site-packages/metakernel/__init__.py", line 2, in <module>
    from ._metakernel import (
  File "/opt/jupyterhub/lib/python3.12/site-packages/metakernel/_metakernel.py", line 40, in <module>
    from IPython.core.excolors import TermColors
ModuleNotFoundError: No module named 'IPython.core.excolors'
`

Reproduced directly outside ansible playbook

**Comment by bcornec** [comment]
> Hummm, however, my test is on a machine where ipython is older: `pip3 list | grep python [...] ipython 8.20.0 [...]`
> 
> So maybe something else :-( It's on a lab machine installed during AlpOSS, so modules have not changed since and it was working there. So maybe another of my very recent modifications.

Anyway, ipython is coming from a package, and has not changed:
`(jupyterhub) wodadmin@wod-backend11:~$ ls -tl /var/lib/dpkg/info/ | grep ipyth
-rw-r--r-- 1 root root    1714 Feb 21 11:22 python3-ipython-genutils.list
-rw-r--r-- 1 root root   19603 Feb 21 11:22 python3-ipython.list
-rw-r--r-- 1 root root    2055 Jan 15  2024 python3-ipython-genutils.md5sums
-rwxr-xr-x 1 root root     283 Jan 15  2024 python3-ipython-genutils.postinst
-rwxr-xr-x 1 root root     396 Jan 15  2024 python3-ipython-genutils.prerm
-rw-r--r-- 1 root root   27811 Jan 15  2024 python3-ipython.md5sums
-rwxr-xr-x 1 root root     265 Jan 15  2024 python3-ipython.postinst
-rwxr-xr-x 1 root root     378 Jan 15  2024 python3-ipython.prerm
`

**Comment by bcornec** [comment]
Ok, so it seems that NeutralColors is not the full caus eof the problem, as it doesn't exist since some time, but that the second error (catch) should not happen:

```
File "/opt/jupyterhub/lib/python3.12/site-packages/metakernel/_metakernel.py", line 40, in <module>
    from IPython.core.excolors import TermColors
ModuleNotFoundError: No module named 'IPython.core.excolors'
```

**Comment by bcornec** [comment]
However: https://github.com/Calysto/metakernel/issues/288

**Comment by bcornec** [comment]
And in fact in the venv, we now use ipython 9 !!
```
(jupyterhub) wodadmin@wod-backend11:~/sshkernel-0.11.1$ pip3 list | grep ipython
ipython                   9.0.0
```

Thus the error. Will try to restict to ipython < 9 meanwhile.

**Comment by bcornec** [comment]
Fix with https://github.com/Workshops-on-Demand/wod-backend/commit/1b401a960c00a9f303a24d28dea35a3683239763

**Comment by bcornec** [comment]
We may review when upstream bug is fixed
